# Formula generated by agent4s release workflow.
# To update: scripts/update-homebrew.sh <version>
class Agent4s < Formula
  desc "Scala superpowers for AI coding agents — 37 commands, no build server"
  homepage "https://github.com/scala-digest/agent4s"
  license "MIT"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/scala-digest/agent4s/releases/download/v#{version}/scalex-macos-arm64"
      sha256 "PLACEHOLDER_SHA256_MACOS_ARM64"
    else
      url "https://github.com/scala-digest/agent4s/releases/download/v#{version}/scalex-macos-x64"
      sha256 "PLACEHOLDER_SHA256_MACOS_X64"
    end
  end

  on_linux do
    url "https://github.com/scala-digest/agent4s/releases/download/v#{version}/scalex-linux-x64"
    sha256 "PLACEHOLDER_SHA256_LINUX_X64"
  end

  def install
    binary = Dir["scalex-*"].first
    bin.install binary => "agent4s"
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/agent4s --version"))
  end
end
